name: CI → Render Deploy (tests then deploy)

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Trigger Render Deploy
        if: ${{ success() }}
        env:
          HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          # Use POST to trigger the deploy hook. Render accepts GET or POST.
          curl -X POST -fsS "$HOOK_URL"
